from .deploysinglecommand import DeploySingleCommand
from .runshellcodecommand import RunShellCodeCommand
from .listdeployedvmscommand import ListDeployedVmsCommand
from .deploymanycommand import DeployManyCommand
